# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
name: Postgresql Build
run-name: ${{ github.actor }} is Build Postgresql 17 Actions
on:
  schedule:
    - cron: "1 10 * * *"
  push:
    branches: [ "main","15","16" ]
    tags:
      - "v*"
  release:
    types: [ created ]
env:
  # Use docker.io for Docker Hub if empty
  GITHUB_REGISTRY: ghcr.io/${{ github.actor }}
  DOCKER_REGISTRY: docker.io/alexbob
  IMAGE_NAME: postgres
  POSTGRES_VERSION: 17
jobs:
  build-image:
    environment: base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAGK_TOKEN }}

      - name: Log into registry docker.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          images: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.POSTGRES_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}